using './web-containerapp.module.bicep'

param acs_outputs_communicationserviceconnectionstring = '{{ .Env.ACS_COMMUNICATIONSERVICECONNECTIONSTRING }}'
param acs_outputs_manageddomainname = '{{ .Env.ACS_MANAGEDDOMAINNAME }}'
param env_outputs_azure_container_apps_environment_default_domain = '{{ .Env.ENV_AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}'
param env_outputs_azure_container_apps_environment_id = '{{ .Env.ENV_AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}'
param env_outputs_azure_container_registry_endpoint = '{{ .Env.ENV_AZURE_CONTAINER_REGISTRY_ENDPOINT }}'
param env_outputs_azure_container_registry_managed_identity_id = '{{ .Env.ENV_AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}'
param postgres_outputs_connectionstring = '{{ .Env.POSTGRES_CONNECTIONSTRING }}'
param postgres_outputs_hostname = '{{ .Env.POSTGRES_HOSTNAME }}'
param storage_outputs_blobendpoint = '{{ .Env.STORAGE_BLOBENDPOINT }}'
param web_containerimage = '{{ .Image }}'
param web_containerport = '{{ targetPortOrDefault 8080 }}'
param web_identity_outputs_clientid = '{{ .Env.WEB_IDENTITY_CLIENTID }}'
param web_identity_outputs_id = '{{ .Env.WEB_IDENTITY_ID }}'
