// <auto-generated />
using System;
using DotGlasses.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotGlasses.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DotGlassesDbContext))]
    [Migration("20260810192836_RemoveInertFlags")]
    partial class RemoveInertFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotGlasses.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HierarchyPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("HierarchyPath");

                    b.HasIndex("HierarchyPath", "FullName");

                    b.HasIndex("HierarchyPath", "PhoneNumber");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("DotGlasses.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("AgeYears")
                        .HasColumnType("integer");

                    b.Property<bool>("ChildrensFrame")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CoatingPreferenceRefId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("boolean");

                    b.Property<bool>("ConvertedFlag")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal?>("CustomAddPowerLeft")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CustomAddPowerRight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CustomAxisLeft")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CustomAxisRight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CustomCylinderLeft")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CustomCylinderRight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CustomSphereLeft")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CustomSphereRight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("HierarchyPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LensOptionLeftId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LensOptionRightId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LensRangeType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OccupationOtherText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OccupationRefId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PresetCatalogueId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PresetPupilDistanceBucket")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PupilDistanceMm")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<string>("ReasonNotPurchasedOtherText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ReasonNotPurchasedRefId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceTestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechnicianUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("HierarchyPath");

                    b.HasIndex("TechnicianUserId");

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("DotGlasses.Domain.Entities.LensOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LensStrengthRefId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PresetCatalogueId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LensStrengthRefId");

                    b.HasIndex("PresetCatalogueId");

                    b.ToTable("LensOptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000001"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000044"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000002"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000046"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000003"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000047"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000004"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000049"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000005"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000052"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000006"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000054"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000007"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000056"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000008"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000058"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000009"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000043"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000010"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000045"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000011"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000046"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000012"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000047"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000013"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000048"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000014"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000049"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000015"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000050"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000016"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000051"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000017"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000053"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000018"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000055"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000019"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000057"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000020"),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000058"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            SortOrder = 11
                        });
                });

            modelBuilder.Entity("DotGlasses.Domain.Entities.LensStrengthCoatingOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoatingRefId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LensStrengthRefId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CoatingRefId");

                    b.HasIndex("LensStrengthRefId");

                    b.HasIndex("LensStrengthRefId", "CoatingRefId")
                        .IsUnique();

                    b.ToTable("LensStrengthCoatingOptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000001"),
                            CoatingRefId = new Guid("b0000000-0000-0000-0000-000000000023"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000055")
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000002"),
                            CoatingRefId = new Guid("b0000000-0000-0000-0000-000000000023"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000056")
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000003"),
                            CoatingRefId = new Guid("b0000000-0000-0000-0000-000000000023"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000057")
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000004"),
                            CoatingRefId = new Guid("b0000000-0000-0000-0000-000000000023"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LensStrengthRefId = new Guid("b0000000-0000-0000-0000-000000000058")
                        });
                });

            modelBuilder.Entity("DotGlasses.Domain.Entities.OrganisationNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("HierarchyPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrainingOrg")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HierarchyPath");

                    b.HasIndex("ParentId");

                    b.ToTable("OrganisationNodes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HierarchyPath = "/1/",
                            IsDeleted = false,
                            IsTrainingOrg = false,
                            Level = 0,
                            Name = "DOT Glasses International"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HierarchyPath = "/1/2/",
                            IsDeleted = false,
                            IsTrainingOrg = false,
                            Level = 1,
                            Name = "Kenya",
                            ParentId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HierarchyPath = "/1/2/3/",
                            IsDeleted = false,
                            IsTrainingOrg = false,
                            Kind = "Retailer",
                            Level = 2,
                            Name = "Kangemi Vision Centre",
                            ParentId = new Guid("a0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HierarchyPath = "/1/2/3/4/",
                            IsDeleted = false,
                            IsTrainingOrg = false,
                            Kind = "Standalone",
                            Level = 3,
                            Name = "Kangemi Vision Centre — Outreach Post",
                            ParentId = new Guid("a0000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("DotGlasses.Domain.Entities.PresetCatalogue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwningOrgNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RangeDescription")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OwningOrgNodeId");

                    b.ToTable("PresetCatalogues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Standard six-option lens range for outlets with local stock.",
                            IsDeleted = false,
                            Name = "6-Lens Set",
                            OwningOrgNodeId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            RangeDescription = "+2.50 to -4.50"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Extended nine-option lens range for outlets with wider stock.",
                            IsDeleted = false,
                            Name = "9-Lens Set",
                            OwningOrgNodeId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            RangeDescription = "+3.00 to -4.00"
                        });
                });

            modelBuilder.Entity("DotGlasses.Domain.Entities.PresetCatalogueAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrgNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PresetCatalogueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrgNodeId");

                    b.HasIndex("PresetCatalogueId");

                    b.HasIndex("PresetCatalogueId", "OrgNodeId")
                        .IsUnique();

                    b.ToTable("PresetCatalogueAssignments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OrgNodeId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OrgNodeId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PresetCatalogueId = new Guid("c0000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("DotGlasses.Domain.Entities.ReferenceDataItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOtherOption")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Code")
                        .IsUnique();

                    b.ToTable("ReferenceDataItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Category = 0,
                            Code = "farmer",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Farmer",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Category = 0,
                            Code = "factory_worker",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Factory worker",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            Category = 0,
                            Code = "teacher",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Teacher",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            Category = 0,
                            Code = "health",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Health worker",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            Category = 0,
                            Code = "salaried",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Other salaried employee",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000006"),
                            Category = 0,
                            Code = "business_owner",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Business owner",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000007"),
                            Category = 0,
                            Code = "labourer",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Casual labour",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000008"),
                            Category = 0,
                            Code = "fundi",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Fundi",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000009"),
                            Category = 0,
                            Code = "retired",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Retired",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000010"),
                            Category = 0,
                            Code = "student",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Student",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000011"),
                            Category = 0,
                            Code = "none",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "No economic activity",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000012"),
                            Category = 0,
                            Code = "other",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = true,
                            Label = "Other",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000013"),
                            Category = 1,
                            Code = "glasses_didnt_help",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "These glasses couldn't help me",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000014"),
                            Category = 1,
                            Code = "dont_need_glasses",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Don't need glasses",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000015"),
                            Category = 1,
                            Code = "price",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Price",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000016"),
                            Category = 1,
                            Code = "no_money",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Don't have the money now",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000017"),
                            Category = 1,
                            Code = "consulting_family",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Needed to consult family",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000018"),
                            Category = 1,
                            Code = "returning_later",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Wanted to return later",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000019"),
                            Category = 1,
                            Code = "want_other_provider",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Preferred another provider",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000020"),
                            Category = 1,
                            Code = "not_convinced_of_benefit",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Not convinced of benefit",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000021"),
                            Category = 1,
                            Code = "other",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = true,
                            Label = "Other",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000022"),
                            Category = 2,
                            Code = "inconclusive",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Inconclusive test result",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000030"),
                            Category = 2,
                            Code = "suspected_eye_disease",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Suspected eye disease",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000031"),
                            Category = 2,
                            Code = "high_prescription",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "High power requirement or outside Dot Glasses range",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000032"),
                            Category = 2,
                            Code = "astigmatism",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Astigmatism",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000033"),
                            Category = 2,
                            Code = "young_child",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Child under eligible age without approval from a specialist",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000034"),
                            Category = 2,
                            Code = "other",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = true,
                            Label = "Other",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000023"),
                            Category = 3,
                            Code = "photochromic",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Photochromic",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000024"),
                            Category = 3,
                            Code = "clear",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Clear",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000025"),
                            Category = 3,
                            Code = "blue_block",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Blue block",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000026"),
                            Category = 3,
                            Code = "polarized",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Polarized",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000027"),
                            Category = 3,
                            Code = "sunglasses",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Sunglasses",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000028"),
                            Category = 4,
                            Code = "black",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Black",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000029"),
                            Category = 4,
                            Code = "blue",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Blue",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000035"),
                            Category = 4,
                            Code = "blue_black",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Blue-Black",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000036"),
                            Category = 4,
                            Code = "brown_black",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Brown-Black",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000037"),
                            Category = 4,
                            Code = "purple",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Purple",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000038"),
                            Category = 4,
                            Code = "purple_black",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Purple-Black",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000039"),
                            Category = 4,
                            Code = "other",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = true,
                            Label = "Other",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000040"),
                            Category = 5,
                            Code = "orange",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Orange",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000041"),
                            Category = 5,
                            Code = "green",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "Green",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000042"),
                            Category = 5,
                            Code = "other",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = true,
                            Label = "Other",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000043"),
                            Category = 6,
                            Code = "plus_3_00",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "+3.00",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000044"),
                            Category = 6,
                            Code = "plus_2_50",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "+2.50",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000045"),
                            Category = 6,
                            Code = "plus_2_00",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "+2.00",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000046"),
                            Category = 6,
                            Code = "plus_1_25",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "+1.25",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000047"),
                            Category = 6,
                            Code = "plus_0_00",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "+0.00",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000048"),
                            Category = 6,
                            Code = "minus_1_00",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "-1.00",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000049"),
                            Category = 6,
                            Code = "minus_1_50",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "-1.50",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000050"),
                            Category = 6,
                            Code = "minus_2_00",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "-2.00",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000051"),
                            Category = 6,
                            Code = "minus_2_50",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "-2.50",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000052"),
                            Category = 6,
                            Code = "minus_3_00",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "-3.00",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000053"),
                            Category = 6,
                            Code = "minus_4_00",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "-4.00",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000054"),
                            Category = 6,
                            Code = "minus_4_50",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "-4.50",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000055"),
                            Category = 6,
                            Code = "bifocal_0_00_3_00",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "+0.00 / +3.00 (Bifocal)",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000056"),
                            Category = 6,
                            Code = "bifocal_0_00_2_50",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "+0.00 / +2.50 (Bifocal)",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000057"),
                            Category = 6,
                            Code = "bifocal_0_00_2_00",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "+0.00 / +2.00 (Bifocal)",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000058"),
                            Category = 6,
                            Code = "bifocal_0_00_1_25",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            IsOtherOption = false,
                            Label = "+0.00 / +1.25 (Bifocal)",
                            SortOrder = 15
                        });
                });

            modelBuilder.Entity("DotGlasses.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("AgeYears")
                        .HasColumnType("integer");

                    b.Property<bool>("ChildrensFrame")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CoatingRefId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal?>("CustomAddPowerLeft")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CustomAddPowerRight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CustomAxisLeft")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CustomAxisRight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CustomCylinderLeft")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CustomCylinderRight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CustomSphereLeft")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CustomSphereRight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FrameColourOtherText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("FrameColourRefId")
                        .HasColumnType("uuid");

                    b.Property<int>("FrameCoverage")
                        .HasColumnType("integer");

                    b.Property<int?>("FulfilmentStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<Guid?>("HardCaseColourRefId")
                        .HasColumnType("uuid");

                    b.Property<string>("HardCaseOtherColourText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("HardCaseSold")
                        .HasColumnType("boolean");

                    b.Property<string>("HierarchyPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LensOptionLeftId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LensOptionRightId")
                        .HasColumnType("uuid");

                    b.Property<int>("LensRangeType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OccupationOtherText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OccupationRefId")
                        .HasColumnType("uuid");

                    b.Property<bool>("OrderFromDotGlasses")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PresetCatalogueId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PresetPupilDistanceBucket")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PupilDistanceMm")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<Guid?>("SourceLeadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechnicianUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("HierarchyPath");

                    b.HasIndex("TechnicianUserId");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("DotGlasses.Domain.Entities.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("AgeYears")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ConvertedToLeadId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("HierarchyPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OccupationOtherText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OccupationRefId")
                        .HasColumnType("uuid");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("ReferralLocationFreeText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReferralOtherText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ReferralReasonRefId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechnicianUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HierarchyPath");

                    b.HasIndex("TechnicianUserId");

                    b.ToTable("Tests", (string)null);
                });

            modelBuilder.Entity("DotGlasses.Domain.Entities.UserOrgAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrgNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrgNodeId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "OrgNodeId")
                        .IsUnique();

                    b.ToTable("UserOrgAssignments", (string)null);
                });

            modelBuilder.Entity("DotGlasses.Domain.Entities.WidgetExample", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("HierarchyPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("HierarchyPath");

                    b.ToTable("WidgetExamples", (string)null);
                });

            modelBuilder.Entity("DotGlasses.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("HierarchyPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastLoginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("OrgLevel")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OrgNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3b1f4a0-1c4a-4a3e-9c1a-000000000001"),
                            ConcurrencyStamp = "f3b1f4a0-1c4a-4a3e-9c1a-000000000001",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("f3b1f4a0-1c4a-4a3e-9c1a-000000000003"),
                            ConcurrencyStamp = "f3b1f4a0-1c4a-4a3e-9c1a-000000000003",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DotGlasses.Domain.Entities.OrganisationNode", b =>
                {
                    b.HasOne("DotGlasses.Domain.Entities.OrganisationNode", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DotGlasses.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DotGlasses.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotGlasses.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DotGlasses.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
