<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DotGlasses.Domain\DotGlasses.Domain.csproj" />
    <ProjectReference Include="..\DotGlasses.Contracts\DotGlasses.Contracts.csproj" />
    <ProjectReference Include="..\DotGlasses.Rules\DotGlasses.Rules.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
